### ISSUE TITLE
Committee logos

### ISSUE THREAD

**Issue by T0m6502** [hoco-etv/flutter-etv-app#14]
Bij personen zie je welke commissies die persoon heeft gedaan. Het zou leuk zijn als elke commissie een logo heeft en dat t logo in de bestuurskleur is van het jaar dat die persoon die commissie gedaan heeft. Doorlopende commissies gwn standaard kleur. 
~ Maxim, Wessel

**Comment by Pwuts** [comment]
Leuk, maar relatief ingewikkeld om te implementeren, en slecht voor de UI aangezien bestuurskleuren bijna alles kunnen zijn.

Wat wel zou kunnen is een Committee-view toevoegen en de commissie-regels op het profiel laten doorverwijzen naar die pagina.
